name: build
on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

env:
  GOLANG_PROTOBUF_REGISTRATION_CONFLICT: ignore

jobs:
  run_build:
    runs-on: ubuntu-latest
    steps:

      - name: clone repo
        uses: actions/checkout@v3

      - name: download and install
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: install protobuf
        run: |
          sudo apt update
          sudo apt install protobuf-compiler

      - name: install dependencies
        run: ./scripts/install_deps

      - name: build linux
        run: ./scripts/build linux amd64 dev

      - name: build darwin
        run: ./scripts/build darwin amd64 dev

      - name: build windows
        run: ./scripts/build windows amd64 dev
