name: tests
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
  workflow_dispatch:

env:
  GOLANG_PROTOBUF_REGISTRATION_CONFLICT: ignore

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: download and install
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: install protoc (protobuf)
        uses: arduino/setup-protoc@v3
        with:
          version: v27.2
          include-pre-releases: false

      - name: chmod to allow run script
        run: chmod +x ./scripts/install_deps

      - name: install dependencies
        run: ./scripts/install_deps

      - name: go tests
        run: go test -v ./...
